"""Add currency column to spending_logs

Revision ID: 4ae57849b93b
Revises: 3b2abf8ff30d
Create Date: 2025-04-15 14:22:56.313743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae57849b93b'
down_revision: Union[str, None] = '3b2abf8ff30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spending_logs', sa.Column('currency', sa.String(length=3), nullable=True,server_default='USD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spending_logs', 'currency')
    # ### end Alembic commands ###
